map:
  resolution: 0.4
  map_x_l: -5
  map_x_u: 20
  map_y_l: -5
  map_y_u: 20

planning:
  target_x: 9.1
  target_y: 2.1
  target_z: 1.5

  step_size: 0.4
  h_surf_car: 0.7

  radius_fit_plane: 2.0

  w_slope: 0.5 #1.0
  w_sparsity: 0.16 # 1.0
  w_bumpiness: 0.83 #2.5
  w_fit_plane: 1.0

  c_slope: 0.33
  c_sparsity: 0.7
  c_bumpiness: 0.18

  ratio_max: 0.4 # 0.1
  ratio_min: 0.02
  conv_thre: 0.1152

  max_initial_time: 2000.0