map:
  resolution: 0.4
  map_x_l: -20.0
  map_x_u: 5.0
  map_y_l: -5.0
  map_y_u: 20.0

planning:
  # target_x: 10.0
  # target_y: 5.0
  # target_z: -1.0

  step_size: 0.4
  h_surf_car: 0.7

  radius_fit_plane: 1.6

  w_slope: 0.33
  w_sparsity: 0
  w_bumpiness: 9.0
  w_fit_plane: 1.0

  c_slope: 0.6
  c_sparsity: 0.5
  c_bumpiness: 0.05

  ratio_max: 0.1
  ratio_min: 0.02
  conv_thre: 0.1152