map:
  resolution: 0.1
  map_x_l: -20.0
  map_x_u: 20.0
  map_y_l: -20.0
  map_y_u: 20.0

planning:
  start_x: 4.0
  start_y: 0.0
  start_z: 0.5
  target_x: 10.0
  target_y: 5.0
  target_z: -1.0

  step_size: 0.3
  h_surf_car: 0.7

  radius_fit_plane: 1.0

  w_flatness: 1000.0
  w_slope: 0.4
  w_sparsity: 0.3
  w_bumpiness: 9.0
  w_fit_plane: 1.0

  c_slope: 0.6
  c_sparsity: 0.1
  c_bumpiness: 0.05

  ratio_max: 0.1
  ratio_min: 0.02
  conv_thre: 0.1152